apiVersion: k3d.io/v1alpha2
kind: Simple
# https://k3d.io/usage/configfile/#all-options-example
# https://github.com/rancher/k3d/blob/main/docs/usage/commands.md

name: playground
servers: 1
agents: 3

kubeAPI: # same as `--api-port myhost.my.domain:6445` (where the name would resolve to 127.0.0.1)
  host: "localhost" # important for the `server` setting in the kubeconfig
  hostIP: "127.0.0.1" # where the Kubernetes API will be listening on
  hostPort: "6445" # where the Kubernetes API listening port will be mapped to on your host system

ports:
  - port: 8080:80 # same as `--port '8080:80@loadbalancer'`
    nodeFilters:
      - loadbalancer

volumes:
  - volume: "/tmp/calico/:/var/lib/rancher/k3s/server/manifests/"

options:
  k3s:
    extraServerArgs: 
      - --no-deploy=traefik     # Using ingress-nginx instead
      - --flannel-backend=none  # Using Calico to support network policies 
    extraAgentArgs: # addditional arguments passed to the `k3s agent` command; same as `--k3s-agent-arg`
    # encountered issues with disk pressure - https://github.com/rancher/k3d/issues/133
    # https://k3d.io/faq/faq/#pods-evicted-due-to-lack-of-disk-space
      - --kubelet-arg=eviction-hard=imagefs.available<1%,nodefs.available<1%
      - --kubelet-arg=eviction-minimum-reclaim=imagefs.available=1%,nodefs.available=1%
