apiVersion: v1
kind: ConfigMap
metadata:
  name: chart-values-argocd
  namespace: argocd
data:
  values-01_HelmChart.yaml: |-
    # https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml
    # global:
    #   image:
    #     tag: v2.10.7

    configs:
      secret:
        argocdServerAdminPassword: $2y$10$tn.V.mXG.rbdJarpxb7weOwD0fLi5zpOgTooVzZzrjBQfi1iVS5i.
        argocdServerAdminPasswordMtime: "2021-03-17T00:15:00Z"

    server:
      extraArgs:
        - --insecure
        - --rootpath
        - /argocd
      ingress:
        enabled: true
        annotations:
          ingress.kubernetes.io/ssl-redirect: "false"
          kubernetes.io/ingress.class: "nginx"
        labels: {}
        ingressClassName: ""
        paths:
          - /argocd
        https: false

# https://raw.githubusercontent.com/rancher/klipper-helm/master/entry
