apiVersion: batch/v1
kind: Job
metadata:
  name: helm-install-argocd
  namespace: argocd
spec:
  backoffLimit: 1000
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        job-name: helm-install-argocd
    spec:
      containers:
      - args:
        - install
        env:
        - name: NAME
          value: argo
        # - name: VERSION
        #   value: 3.31.0
        - name: REPO
          value: https://argoproj.github.io/argo-helm
        # - name: HELM_DRIVER
        #   value: secret
        - name: CHART_NAMESPACE
          value: argocd
        - name: CHART
          value: argo/argo-cd
        - name: HELM_VERSION
        image: rancher/klipper-helm:v0.4.3
        imagePullPolicy: IfNotPresent
        name: helm
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: values
        - mountPath: /chart
          name: content
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: helm-argocd
      serviceAccountName: helm-argocd
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: chart-values-argocd
        name: values
      - configMap:
          defaultMode: 420
          name: chart-content-argocd
        name: content
